### PR TITLE
Adopt flux-instance from upstream

### PR DESCRIPTION
**Pull request by kingdonb**
Builds on #362 

The main issue we will have to solve (maybe with a patch) is that `cluster.domain` is always specified in this chart;

I'm reading to try to recall how we solved this last time.

## Release Notes

- **New Features**
	- Updated the Flux Operator Helm chart to version 0.9.0, introducing enhanced configuration options for service monitoring and resource management.
	- Added a new `ServiceMonitor` resource for Prometheus integration.
	- Introduced a `serviceMonitor` configuration option with default values for scraping settings.
	- New `FluxInstance` resource configuration file added for deploying a Flux instance.

- **Documentation**
	- Updated README files to reflect new version and provide installation instructions for the Flux instance.
	- Added a `NOTES.txt` file directing users to Flux CD operator documentation.

- **Bug Fixes**
	- Corrected links in documentation and ensured proper metadata for the new chart.

- **Chores**
	- Restructured configuration files for improved organization and clarity.
	- Introduced a `.helmignore` file to streamline package building.

### CODE REVIEW

**Comment by kingdonb** [comment]
Oh, we used this `kustomize.patches` patch, which is preserved by this upgrade:

```
    - target:
        kind: Deployment
        name: (kustomize-controller|helm-controller|image-reflector-controller|image-automation-controller)
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --events-addr=http://notification-controller.cozy-fluxcd.svc/
```

^ Setting the events-addr like this negates the impact of a default cluster domain, so we can let the default value be `cluster.local` and it won't be used.

**Comment by kvaps** [comment]
Hi @kingdonb just been merged, could you please rebase?

**Comment by kingdonb** [comment]
So, the impact of this upgrade is:

```yaml
artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest
```

^ This value is added, enabling the automatic update functionality

```

For an idea of what's in there, you can unpack the artifact and inspect it:
```
% flux pull artifact oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest --output ./test
► pulling artifact from ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:latest
✔ source git://github.com/controlplaneio-fluxcd/flux-operator.git
✔ revision v0.9.0@sha1:cfb54b373ac10f2f747085cba0cb619a0ad4084e
✔ digest ghcr.io/controlplaneio-fluxcd/flux-operator-manifests@sha256:dbbe54551c121d4d06d16f9cba5680545b90bb9be33cbfb371b5bdab8a421b33
✔ artifact content extracted to ./test

% tree test/
test/
├── flux
│   ├── v2.2.3
│   │   ├── helm-controller.yaml
│   │   ├── image-automation-controller.yaml
│   │   ├── image-reflector-controller.yaml
│   │   ├── kustomize-controller.yaml
│   │   ├── notification-controller.yaml
│   │   ├── policies.yaml
│   │   ├── rbac.yaml
│   │   └── source-controller.yaml
│   └── v2.3.0
│       ├── helm-controller.yaml
│       ├── image-automation-controller.yaml
│       ├── image-reflector-controller.yaml
│       ├── kustomize-controller.yaml
│       ├── notification-controller.yaml
│       ├── policies.yaml
│       ├── rbac.yaml
│       └── source-controller.yaml
├── flux-images
│   ├── VERSION
│   ├── v2.2.0
│   │   ├── enterprise-alpine.yaml
│   │   ├── enterprise-distroless.yaml
│   │   └── upstream-alpine.yaml
│   ├── v2.2.1
│   │   ├── enterprise-alpine.yaml
│   │   ├── enterprise-distroless.yaml
│   │   └── upstream-alpine.yaml
│   ├── v2.2.2
│   │   ├── enterprise-alpine.yaml
│   │   ├── enterprise-distroless.yaml
│   │   └── upstream-alpine.yaml
│   ├── v2.2.3
│   │   ├── enterprise-alpine.yaml
│   │   ├── enterprise-distroless.yaml
│   │   └── upstream-alpine.yaml
│   └── v2.3.0
│       ├── enterprise-alpine.yaml
│       ├── enterprise-distroless.yaml
│       └── upstream-alpine.yaml
└── flux-operator
    └── install.yaml
```

... all of the details flux-operator needs to keep Flux up-to-date in conformance with your setting in spec (ours is currently `2.3.x`)

**Comment by kingdonb** [comment]
👍 rebased - the Flux 2.4 release should land probably on Monday next week, so we'll be ready for that

**Review by kvaps — APPROVED** [review]
LGTM

**Comment by kvaps** [comment]
Thank you!

**Pull request merged**
