### PR TITLE
Ship all logos with Cozystack

### PR DESCRIPTION
**Pull request by kvaps**
Add all application logos into the cozystack container. Please merge it after https://github.com/aenix-io/cozystack/pull/217

image

### CODE REVIEW

**Review by themoriarti — COMMENTED** [review]
Such an approach to deliver everything with cozystack packages is not very good, considering the large number of files that do not carry the direct functionality of the product, we still give customers the opportunity to download helm charts, images, etc. Why can't customers download images and other auxiliary files from another repository? There are specialized CDNs for such purposes. Therefore, it is possible to separate repositories of utilities, tools, image graphics, auxiliary files, articles, etc.

**Comment by kvaps** [comment]
These logos are part of Helm charts delivered by cozystack container.
They are required to make Dashboard working in air-gaped installations.
Logos are in SVG and should not take much space.

Filally we want to make cozystack fully undepended from external sources, including docker images in the future.

**Comment by themoriarti** [comment]
@kvaps But images is a part of dashboard, maybe we need store this logos in dashboard chart?

**Comment by kvaps** [comment]
I thought about this, but it might be difficult to recompile dashboard image every time we need to add new logo.
From the other side logos now stored in the same HTTP server with Helm charts.
Dashboard is useless in case it can't reach Helm charts. So we need this HTTP server any way.

We have this HTTP server for all assets like helm-charts, grafana dashboards and now also logos.

**Review by themoriarti — APPROVED** [review]
If this incident of adding files that are not related to the functionality does not entail the addition of other files to the helm chart, then no, now I understand the approach. But I still recommended to physically store them in another repository and thus we can also download them for the HTTP server.

**Pull request merged**
