### PR TITLE
Prepare release v0.4.0

### PR DESCRIPTION
**Pull request by kvaps**

### CODE REVIEW

**Review by themoriarti — COMMENTED** [review]
Why [main](https://github.com/aenix-io/cozystack/tree/main) from [release-0.1.0v2](https://github.com/aenix-io/cozystack/tree/release-0.1.0v2) ? Maybe typo error?

**Review by themoriarti — COMMENTED** [review]
[release-0.1.0v2](https://github.com/aenix-io/cozystack/tree/release-0.1.0v2) why not 0.4.0v2 ?

**Comment by kvaps** [comment]
Just made a typo in a branch name, it is not critical as GitHub does not mentoin it anywhere after it get merged

**Review by themoriarti — APPROVED** [review]
Ok, lets go release.

**Pull request merged**
