### PR TITLE
SeaweedFS

### PR DESCRIPTION
**Pull request by kvaps**
This PR adds SeaweedFS

### CODE REVIEW

**Review by themoriarti — APPROVED** [review]
This is a very good idea, now we will have a choice.

**Comment by Rjvs** [comment]
Is this going to be merged?

**Comment by themoriarti** [comment]
@kvaps I would try with cocroachdb, this combination is quite interesting. What are your thoughts on this?

**Comment by kvaps** [comment]
If it is not licensed as free software (BSL doesn't count), then we can't adopt it
https://www.cockroachlabs.com/docs/stable/licensing-faqs

**Pull request merged**
