### PR TITLE
Added external-secrets-operator

### PR DESCRIPTION
**Pull request by mrkhachaturov**
This pull request adds the external-secrets-operator to our main bundles. By integrating the external-secrets-operator, we enable seamless connectivity to external hosted secret management services such as HashiCorp Vault, 1Password, AWS Secrets Manager, and more.

Benefits:

Unified Secret Management: Allows the application to securely fetch secrets from external providers without hardcoding them into configurations.
Flexibility: Supports multiple external secret stores, giving users the freedom to choose their preferred secret management solution.
Enhanced Security: Reduces the risk of exposing sensitive information by leveraging established secret management platforms.

## Summary by CodeRabbit

- **New Features**
	- Introduced the `external-secrets-operator` for managing external secrets in Kubernetes.
	- Added a Helm chart for the `external-secrets` application, including configuration options and dependencies.
	- Implemented a certificate controller within the external-secrets-operator.

- **Documentation**
	- Added README.md with installation instructions and configuration options for the External Secrets Operator.
	- Included success message and setup instructions in NOTES.txt for the external-secrets deployment.

- **Chores**
	- Created .helmignore to streamline Helm packaging by excluding unnecessary files.

### CODE REVIEW

**Comment by kvaps** [comment]
Hi @mrkhachaturov, thank you for contibution this is nice enhancement, could you please clarify your use-case?
How exacly are you going to use ESO?

**Comment by mrkhachaturov** [comment]
Hi @kvaps ,

Thank you for your feedback and for considering this enhancement. I'm happy to clarify our use case and explain the benefits of using the External Secrets Operator (ESO).

**Use Case and Rationale:**

In our deployment, we utilize external secret management services like HashiCorp Vault or 1Password to securely store and manage secrets and credentials. Our goal is to integrate these external services with our Kubernetes cluster to centralize secret management, enhance security, and streamline secret rotation and auditing.

**How We Use ESO:**

The External Secrets Operator enables seamless integration between Kubernetes and external secret management systems. Here's how we leverage ESO:

Connecting to External Secret Managers: We configure ESO to connect to our external secret management service (e.g., 1Password Connect) using a `ClusterSecretStore`. This setup allows Kubernetes to fetch secrets directly from the external store without embedding them in code or configuration files.
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: production
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.example.net
      vaults:
        Production: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            key: token
            namespace: cozy-external-secrets-operator
 ```           
Defining External Secrets: With ESO connected to our external secret manager, we define ExternalSecret resources within our Git repositories. These resources specify which secrets to fetch and how to project them into Kubernetes secrets.
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confdb-backup
  namespace: confluence
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: production
  target:
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: Confluence_DB
        property: s3_access_key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: Confluence_DB
        property: s3_secret_key
    - secretKey: REGION
      remoteRef:
        key: Confluence_DB
        property: s3_region
 ```       
**Safe Application Bootstrapping:** ESO ensures that applications can access the required secrets without exposing sensitive information. Secrets are automatically synced from the external store to Kubernetes, allowing services to consume them securely during startup and operation.

**Benefits of Using ESO:**

- **Centralized Secret Management:**

  - Unified Control: Manage all secrets in a central external store, simplifying administration across multiple clusters and environments.

  - Consistent Practices: Apply consistent secret management policies and procedures, enhancing compliance and governance.

- **Enhanced Security:**
  - **Reduced Exposure Risk**: Secrets are not stored in Kubernetes manifests or code repositories, minimizing the risk of accidental leaks.
  - **Robust Access Controls**: Leverage the advanced authentication and authorization features of external secret managers to control access to secrets.

- **Operational Efficiency**:
  - **Automated Synchronization**: ESO automatically syncs secrets from the external store to Kubernetes, reducing manual intervention and potential for errors.
  - **Simplified Rotation**: Secret updates in the external manager are automatically reflected in Kubernetes, facilitating seamless secret rotation without redeploying applications.

- **Flexibility and Scalability**:
  - **Multi-Provider Support:** ESO supports various external secret management systems, providing flexibility to use different providers as needed.
  - **Scalable Architecture**: Integrate with external services without overloading Kubernetes with secret management tasks, promoting better performance and scalability.

- **Seamless GitOps Integration:**
  - **Declarative Configuration**: Define secrets and their mappings in code repositories, enabling version control and auditability.
  - **Safe Bootstrap Process**: Initialize and bootstrap applications using secrets managed externally, ensuring a secure startup process.

**Conclusion:**

Integrating the External Secrets Operator into our deployment brings significant benefits:

**Security**: Enhanced protection of sensitive information by leveraging secure external storage and limiting in-cluster secret exposure.
**Efficiency**: Streamlined secret management processes with automated synchronization and simplified rotation.
**Flexibility**: Ability to work with various external secret providers, adapting to organizational needs and preferences.

By using ESO, we improve our cluster's security posture and operational efficiency while maintaining flexibility in our choice of secret management solutions.

Please let me know if you have any further questions or need additional details.

**Comment by kvaps** [comment]
Got it. So you don't expect deeper integration with existing charts for now, and you're going to use for your busines application logic.

It seems it might be really useful also as addon for copying secrets from management Kubernetes to tenant Kubernetes clusters.

Thank you. I will review this in a while.

**Comment by mrkhachaturov** [comment]
> Got it. So you don't expect deeper integration with existing charts for now, and you're going to use it only for your busines application logic?
> 
> It seems it might be really useful also as addon for copying secrets from management Kubernetes to tenant Kubernetes clusters.
> 
> Thank you. I will review this in a while.

We find the use case relevant where we use CozyStack to build a private cloud.

In each tenant, teams can create different ClusterSecrets stores, or we can provide the option to use the ClusterSecrets store from the upper tenant.

I am currently working on refining the logic and will send another PR later.

**Pull request merged**
